// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SIENN.DbAccess.Models;
using System;

namespace SIENN.WebApi.Migrations
{
    [DbContext(typeof(SIENNDbContext))]
    [Migration("20171226153405_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SIENN.DbAccess.Models.CategoryProduct", b =>
                {
                    b.Property<Guid>("CategoryCode");

                    b.Property<Guid>("ProductCode");

                    b.HasKey("CategoryCode", "ProductCode");

                    b.HasIndex("ProductCode");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("SIENN.DbAccess.Models.Product", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsAvailable");

                    b.Property<decimal>("Price");

                    b.Property<Guid>("TypeCode");

                    b.Property<Guid>("UnitCode");

                    b.HasKey("Code");

                    b.HasIndex("TypeCode");

                    b.HasIndex("UnitCode");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SIENN.DbAccess.Models.ProductCategory", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Code");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SIENN.DbAccess.Models.ProductType", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Code");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("SIENN.DbAccess.Models.ProductUnit", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Code");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("SIENN.DbAccess.Models.CategoryProduct", b =>
                {
                    b.HasOne("SIENN.DbAccess.Models.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SIENN.DbAccess.Models.Product", "Product")
                        .WithMany("Categories")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SIENN.DbAccess.Models.Product", b =>
                {
                    b.HasOne("SIENN.DbAccess.Models.ProductType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SIENN.DbAccess.Models.ProductUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
