// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SIENN.DbAccess.Models;
using System;

namespace SIENN.WebApi.Migrations
{
    [DbContext(typeof(SIENNDbContext))]
    [Migration("20171226120944_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SIENN.DbAccess.Models.Product", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsAvailable");

                    b.Property<decimal>("Price");

                    b.HasKey("Code");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SIENN.DbAccess.Models.ProductCategory", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid?>("ProductCode");

                    b.HasKey("Code");

                    b.HasIndex("ProductCode");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SIENN.DbAccess.Models.ProductType", b =>
                {
                    b.Property<Guid>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Code");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("SIENN.DbAccess.Models.ProductUnit", b =>
                {
                    b.Property<Guid>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Code");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("SIENN.DbAccess.Models.ProductCategory", b =>
                {
                    b.HasOne("SIENN.DbAccess.Models.Product")
                        .WithMany("Categories")
                        .HasForeignKey("ProductCode");
                });

            modelBuilder.Entity("SIENN.DbAccess.Models.ProductType", b =>
                {
                    b.HasOne("SIENN.DbAccess.Models.Product")
                        .WithOne("Type")
                        .HasForeignKey("SIENN.DbAccess.Models.ProductType", "Code")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SIENN.DbAccess.Models.ProductUnit", b =>
                {
                    b.HasOne("SIENN.DbAccess.Models.Product")
                        .WithOne("Unit")
                        .HasForeignKey("SIENN.DbAccess.Models.ProductUnit", "Code")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
